### PR TITLE
LPS-63032 Add new attribute to the search container to decide whether to use minimal styling for displaying empty results message

### PR DESCRIPTION
**Pull request by pei-jung**
Hi Jim,

Brian asked me to send this to your way. Can you please take a look at abffeb30f0068b34e8319584eb0f7ee4c415c1f5? Thanks!

### CODE REVIEW

**Comment by jhinkey** [comment]
Reviewing now. Thank you @pei-jung !

**Comment by jhinkey** [comment]
@pei-jung ,

If these two booleans are set to false (or left to the false default values), is the styling of the cssClass still applied to search-container's empty search results and the empty search message? If the booleans are set to true, does the minimal styling supersede the cssClass styling for the empty search results and empty search message?

Thank you.

**Comment by pei-jung** [comment]
Hey @jhinkey,

The styling of the cssClass should still applied regardless of the value of the boolean. The default styling for the empty search results and empty search message has the big face icon, the minimal styling removes that icon and displays just the text message. Let me know if you have other questions. Thanks!

**Comment by jhinkey** [comment]
Excellent! Thank you, Pei-Jung.

On 2/29/2016 2:24 PM, Pei-Jung Lan wrote:
>
> Hey @jhinkey <https://github.com/jhinkey>,
>
> The styling of the cssClass should still applied regardless of the
> value of the boolean. The default styling for the empty search results
> and empty search message has the big face icon, the minimal styling
> removes that icon and displays just the text message. Let me know if
> you have other questions. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhinkey/liferay-portal/pull/334#issuecomment-190344626>.
>

-- 
Jim Hinkey
Sr. Knowledge Engineer
Liferay, Inc.
www.liferay.com <http://www.liferay.com>

Visit Us: www.liferay.com <http://www.liferay.com> | Like Us:
facebook.com/liferay <http://facebook.com/liferay> | Follow Us:
twitter.com/liferay <http://twitter.com/liferay>

**Comment by jhinkey** [comment]
Sent https://github.com/brianchandotcom/liferay-portal/pull/36854

**Pull request merged**
