### PR TITLE
LRDOCS-2174 Add Javadoc for Facebook Connect SSO Authentication module

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LRDOCS-2174 Add Javadoc for Facebook Connect SSO Authentication module

### CODE REVIEW

**Comment by jrao** [comment]
@stian-sigvartsen FYI, here's the Facebook authentication Javadoc

**Comment by jrao** [comment]
@jhinkey I fixed the format errors, this should be good to go.

**Comment by jhinkey** [comment]
Started reviewing. thanks

**Comment by jhinkey** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/35664

**Pull request closed without merging**
