### PR TITLE
LPS-70911 Wording help

### PR DESCRIPTION
**Pull request by tomwang2011**
Hello Jim,

We have inlined some jsp files to improve performance. We know that some customers have hooks to replace these jsp files with their own version. We still want to support that by adding these .readme files to where the jsp used to be. The customer can remove the .readme extension and use the files like before (our inlined sections will not run if we detect the jsp file is present). 

We are hoping you can help us with the wording in this .readme file to clearly express this change to clients reading these readme files. 

I only sent over one sample case in the last commit, I will replace all the removed jsp files after the wordsmithing.

Thanks!

CC @shuyangzhou

### CODE REVIEW

**Comment by jhinkey** [comment]
Hi Tom @tomwang2011,

Please confirm if this is the new logic:

If the JSP file (the one that currently ends in .readme) ending in .jsp exists
Then use that JSP file's content
Else use the inline content

Are these optimizations only being implemented for some taglib tags (such as this liferay-theme:layout-icon tag) or are they also happening in other places?

cc/ @shuyangzhou

**Comment by jhinkey** [comment]
Also, is this change being introduced for ee-7.0.x and  7.0.x?

cc/ @shuyangzhou

**Comment by tomwang2011** [comment]
Hi Jim, this will happen in other places as well. Also this change will also apply to ee-7.0.x and 7.0.x.

Thanks!

**Comment by jhinkey** [comment]
@mwilliams2014 will help with this. [https://issues.liferay.com/browse/LRDOCS-3507](https://issues.liferay.com/browse/LRDOCS-3507)

**Comment by jhinkey** [comment]
Sent via https://github.com/tomwang2011/liferay-portal/pull/285

**Pull request closed without merging**
