### PR TITLE
LPS-56451 Javadoc for render command

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Jim,

This is javadoc for some extensions that we did in the MVCPortlet framework to allow developers to have more control and organization in their own MVC portlets. 

It would be great if we could also create a tutorial out of this explaining how to create MVC portlets using this new mechanism.

Sergio

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @izaera

**Comment by sergiogonzalez** [comment]
cc/ @izaera

**Comment by jhinkey** [comment]
reviewing now. Thanks.

**Comment by jhinkey** [comment]
Thank you.
Sent edits in https://github.com/brianchandotcom/liferay-portal/pull/27963.
Created https://issues.liferay.com/browse/LRDOCS-1795 for tutorial(s).

**Pull request closed without merging**
