### PR TITLE
https://issues.liferay.com/browse/LRDOCS-2078 Add Javadoc to TokenAuthentication classes

### PR DESCRIPTION
**Pull request by jrao**
LRDOCS-2078 Add Javadoc to TokenAuthentication classes

### CODE REVIEW

**Comment by jrao** [comment]
@stian-sigvartsen FYI, here's a pull request adding some of the documentation from your Token SSO Authentication doc as Javadoc.

**Comment by jhinkey** [comment]
Started reviewing.

**Comment by jhinkey** [comment]
Sent https://github.com/brianchandotcom/liferay-portal/pull/32441

**Comment by jhinkey** [comment]
@jrao please see the minor changes I made in the PR. Thanks.

**Pull request closed without merging**
