### PR TITLE
pull-request-2413

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @jhinkey 

Can you test my changes?

Thanks!

**Comment by hhuijser** [comment]
Looking at this a bit more, it probably would make sense to move this to SF.
One concern. In FileUploadChannelHandlerTest.java it changes stuff that's inside quotes.

**Comment by jhinkey** [comment]
Yep, I'll see about moving it to SF and look into handling stuff in quotes. Thanks!

**Comment by jhinkey** [comment]
Still working on it. Thanks.

**Comment by jhinkey** [comment]
Sent https://github.com/jhinkey/liferay-portal/pull/241

**Pull request closed without merging**
