### PR TITLE
LRDOCS-2594 Applied DXP styles to Javadoc

### PR DESCRIPTION
**Pull request by mwilliams2014**
@jhinkey can you review these styles? Once you give the ok, I can resend to the proper branch, if this isn't it. thx!

FYI these styles are not formatted to Liferay's guidelines, so please send back to me after your review. thx!

### CODE REVIEW

**Comment by jhinkey** [comment]
Thanks Mike. Reviewing now.

**Comment by mwilliams2014** [comment]
@jhinkey I've updated the styles to use the proper stylesheet now, and added a custom gradient. Please let me know what you think. thx!

**Comment by jhinkey** [comment]
Started reviewing. Thanks.

**Comment by jhinkey** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/39864

**Pull request closed without merging**
