### PR TITLE
https://issues.liferay.com/browse/LRDOCS-2113 Add Javadoc for OpenID SSO module

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LRDOCS-2113 Add Javadoc for OpenID SSO module

### CODE REVIEW

**Comment by jrao** [comment]
@jhinkey Hi Jim, this is ready for you to review

**Comment by jhinkey** [comment]
Great!

**Comment by jhinkey** [comment]
Started reviewing. Thanks.

**Comment by jhinkey** [comment]
Sent https://github.com/brianchandotcom/liferay-portal/pull/33331

**Pull request closed without merging**
