### PR TITLE
LPS-58040 Journal lang keys

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/32503#issuecomment-159018974

**Comment by jhinkey** [comment]
Started reviewing. Thanks.

**Comment by jhinkey** [comment]
Sent https://github.com/brianchandotcom/liferay-portal/pull/32527

**Comment by jhinkey** [comment]
Thanks @inacionery !

**Pull request closed without merging**
