### PR TITLE
LPS-60366 Readd Javadoc

### PR DESCRIPTION
**Pull request by jrao**
LPS-60366 Readd Javadoc

### CODE REVIEW

**Comment by jhinkey** [comment]
Hi Jesse. I haven't reviewed your Javadoc yet. But if you haven't done so already, please make sure to run `format-javadoc` with ` -Dupdate=true` and describe any params/exceptions it adds. Thanks.

**Comment by jrao** [comment]
Will do.

**Comment by jhinkey** [comment]
Merged locally. Thanks, Jesse.

**Comment by jhinkey** [comment]
Sent https://github.com/brianchandotcom/liferay-portal/pull/32440

**Pull request closed without merging**
