### PR TITLE
LPS-59681

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@jhinkey if you can take a look @ the breakchanges in the last commit (bef11c1)

Cheers

**Comment by jhinkey** [comment]
Yes, Mike. I'll take a look right away. - Jim

On 10/27/2015 11:39 AM, Michael Han wrote:
>
> @jhinkey <https://github.com/jhinkey> if you can take a look @ the
> breakchanges in the last commit (bef11c1
> <https://github.com/jhinkey/liferay-portal/commit/bef11c1a635c3a76f9893280f065f75d92b79be5>)
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhinkey/liferay-portal/pull/279#issuecomment-151544437>.
>

-- 
Jim Hinkey
Sr. Knowledge Engineer
Liferay, Inc.
www.liferay.com <http://www.liferay.com>

*Liferay Symposium North America*
November 16-17, 2015 | Chicago, IL
www.liferay.com/northamerica2015 <http://www.liferay.com/northamerica2015>
---

Visit Us: www.liferay.com <http://www.liferay.com> | Like Us:
facebook.com/liferay <http://facebook.com/liferay> | Follow Us:
twitter.com/liferay <http://twitter.com/liferay>

**Comment by jhinkey** [comment]
Started reviewing. Thanks.

**Comment by jhinkey** [comment]
@codyhoag - FYI - I'm editing Mike Han's breaking change and another breaking change that's been added recently.

**Comment by codyhoag** [comment]
Thanks for the heads up @jhinkey.

**Comment by jhinkey** [comment]
Sent to Mike https://github.com/mhan810/liferay-portal/pull/809

**Pull request closed without merging**
