### PR TITLE
LPS-65831 Add information about file separators

### PR DESCRIPTION
**Pull request by mdelapenya**
cc/ @migue @alee8888 @vicnate5

### CODE REVIEW

**Comment by jhinkey** [comment]
Started reviewing

**Comment by jhinkey** [comment]
@mdelapenya - Would you please add under your first heading a short description (sentence or two) describing this tool--the Data Partitioning SQL Builder and push to this branch?

**Comment by mdelapenya** [comment]
Hi @jhinkey @migue, I pushed a new commit with main purpose of the tool. Hope it helps 😃

**Comment by jhinkey** [comment]
Started reviewing. Thank you.

**Comment by jhinkey** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/39898

**Pull request closed without merging**
